medical_app/laboratory/urls.py
from django.urls import include, path

from .views import laboratory, specialists, patients
from cart.views import CartItemDeleteView, cart_details_view, CartItemUpdateView
from orders.views import order_checkout, UserOrdersListView, OrdersListView, edit_order_items, OrdersDetailView


from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from users.decorators import specialist_required, patient_required


urlpatterns = [
    path('', laboratory.home, name='home'),

    path('specialists/', decorator_include(
        (login_required, specialist_required), include(
            (
                [
                    path('surveys/', specialists.SurveyListView.as_view(), name='survey_list'),
                    path('surveys/add/', specialists.SurveyCreateView.as_view(), name='survey_add'),
                    path('surveys/<int:pk>/update/', specialists.AssignParamsToSurveyView.as_view(),
                       name='survey_update'),
                    path('surveys/<int:pk>/delete/', specialists.SurveyDeleteView.as_view(),
                       name='survey_delete'),
                    path('parameters/add/', specialists.ParameterCreateView.as_view(),
                       name='parameter_add'),

                    path('orders/', OrdersListView.as_view(), name='orders_list'),
                    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='orders_detail'),
                    path('orders/orderitem/<int:pk>/', CartItemUpdateView.as_view(), name='orders_items_update'),

                ],
                'laboratory'
            ),
            namespace='specialists'
        )
    )),


    path('patients/', decorator_include(
        (login_required, patient_required), include(([
            path('surveys/', patients.SurveyListView.as_view(), name='survey_list'),
            path('surveys/<int:pk>/', patients.OrderSurveyWithParams.as_view(), name='survey_order'),
            path('cart/', cart_details_view, name='cart_details'),
            path('cart/delete_item/<int:pk>/', CartItemDeleteView.as_view(), name='cart_item_delete'),
            path('order/checkout/', order_checkout, name='order_checkout'),
            path('order/history/', UserOrdersListView.as_view(), name='order_list')
        ], 'laboratory'), namespace='patients'))),

]

medical_app/medical_app/urls.py
from django.contrib import admin
from django.urls import include, path

from users.views import users_laboratory, users_patients, users_specialists  # authentication views

urlpatterns = [
    path('', include('laboratory.urls')),  # domain views
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', users_laboratory.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patient/', users_patients.PatientSignUpView.as_view(), name='patient_signup'),
    path('accounts/signup/teacher/', users_specialists.SpecialistSignUpView.as_view(), name='specialist_signup'),

    path('admin/', admin.site.urls),

]

medical_app/cart/models.py
from django.db import models
from laboratory.models import Survey, Parameter
from users.models import User


class Cart(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    ordered_at = models.DateTimeField(null=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f"Cart id: {self.pk}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='cart_items', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='cart_items', on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey, related_name='survey_orders', on_delete=models.CASCADE)

    # parameters are here as ParameterWIthResult table, because we need to assign additional field "result" to it
    parameters = models.ManyToManyField(Parameter, through="ParameterWithResult", related_name='parameter_orders', null=True)

    finished_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'Cart Item id {self.pk} '


class ParameterWithResult(models.Model):
    cart_item = models.ForeignKey(CartItem, on_delete=models.CASCADE, related_name='parameters_results')
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE)
    result = models.CharField(max_length=50, null=True)

medical_app/cart/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import CartItem, ParameterWithResult


class ParameterWithResultForm(forms.ModelForm):

    class Meta:
        model = ParameterWithResult
        exclude = ()


class EditParameterWithResultForm(forms.ModelForm):

    class Meta:
        model = ParameterWithResult
        fields = ('parameter', 'result')


EditParameterWithResultFormSet = forms.modelformset_factory(
    ParameterWithResult, fields=('parameter', 'result'), extra=0, form=EditParameterWithResultForm)


ParameterWithResultFormSet = inlineformset_factory(
    CartItem, ParameterWithResult, form=ParameterWithResultForm,
    fields=('parameter', 'result'), extra=0,
)

medical_app/cart/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import DeleteView, UpdateView
from .models import CartItem, ParameterWithResult
from .cart import get_cart_details_context
from .forms import EditParameterWithResultForm, EditParameterWithResultFormSet
from django.urls import reverse_lazy


class CartItemDeleteView(DeleteView):
    model = CartItem
    template_name = 'cart/cartitem_confirm_delete.html'
    success_url = reverse_lazy('patients:cart_details')

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only owner of this CartItem can delete """
        obj = self.get_object()
        try:
            the_id = self.request.session[settings.CART_SESSION_ID]
        except:
            the_id = None
        if not the_id or obj.cart.id != the_id:
            messages.error(request, 'Document not deleted.')
            return redirect('patients:cart_details')
        return super(CartItemDeleteView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Survey deleted from your order")
        return super(CartItemDeleteView, self).delete(request, *args, **kwargs)


def cart_details_view(request):
    context = get_cart_details_context(request)
    template = 'cart/detail_view.html'
    return render(request, template, context)


class CartItemUpdateView(UpdateView):
    model = ParameterWithResult
    form_class = EditParameterWithResultForm
    template_name = 'cart/cartitem_update_results.html'


    def get_object(self, queryset=None):
        return self.get_cartitem()

    def get_queryset(self):
        return ParameterWithResult.objects.filter(cart_item=self.get_cartitem())

    def get_cartitem(self):
        cartitem_pk = self.kwargs.get('pk')
        return CartItem.objects.get(pk=cartitem_pk)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        formset = EditParameterWithResultFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        return self.form_invalid(request, formset)

    def form_invalid(self, request, formset):
        return render(request, self.template_name, {"formset": formset})

    def form_valid(self, form):
        for single_form in form:
            instance = single_form.save(commit=False)
            instance.cart_item = self.get_cartitem()
            instance.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['cart_item'] = self.get_cartitem()
        ctx['formset'] = EditParameterWithResultFormSet(queryset=self.get_queryset())
        return ctx

    def get_success_url(self):
        messages.success(self.request, "Surveys results updated!")
        return reverse_lazy('specialists:orders_items_update', kwargs={'pk': self.kwargs.get('pk')})

medical_app/cart/templates/cart/cartitem_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete cart item</legend>
                <h2>Are you sure you want to delete the survey "{{ object.survey.name }}" from your order?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'patients:cart_details' %}">Cancel</a>

            </div>

        </form>
    </div>
{% endblock content %}

medical_app/cart/templates/cart/cartitem_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            Fill results of the surveys
            <br>Parameter, User and Survey should not be allowed to change, it should be static, based on the query
        </div>
        <div class="card-body">
             {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

medical_app/cart/templates/cart/cartitem_update_results.html
{% extends 'base.html' %}

{% block content %}
    {{ block.super }}

    <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for single_form in formset %}

            {{ single_form.as_p }}
        {% endfor %}
        <div><button type="submit" class="btn btn-primary">Save</button></div>
    </form>

{% endblock %}

medical_app/cart/templates/cart/detail_view.html
{% extends 'base.html' %}
{% block title %}
    Your Order
{% endblock %}


{% block content %}
{% if empty %}
    <h1>{{ empty_message }}</h1>
{% else %}


    <div class="container">
        <div class="row" style="margin-top: 6%">
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Survey</th>
                        <th>Parameters </th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart.cart_items.all %}
                    {% with survey=item.survey %}
                        <tr>
                            <td>
                                {{ survey.name }}
                            </td>
                            <td>All: {{ item.parameters.count }}</td>
                            <td>
                                <a href="{% url 'patients:cart_item_delete' item.pk %}">Remove</a>
                            </td>
                        </tr>
                        {% for parameter in item.parameters.all %}
                            <tr>
                                <td></td>
                                <td>{{ parameter.name }}</td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>{{ cart.cart_items.count }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url 'patients:survey_list' %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url 'patients:order_checkout' %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endif %}
{% endblock %}