medical_app/laboratory/urls.py
from django.urls import include, path

from .views import laboratory, specialists, patients
from cart.views import CartItemDeleteView, cart_details_view, CartItemUpdateView
from orders.views import order_checkout, UserOrdersListView, OrdersListView, edit_order_items, OrdersDetailView


from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from users.decorators import specialist_required, patient_required


urlpatterns = [
    path('', laboratory.home, name='home'),

    path('specialists/', decorator_include(
        (login_required, specialist_required), include(
            (
                [
                    path('surveys/', specialists.SurveyListView.as_view(), name='survey_list'),
                    path('surveys/add/', specialists.SurveyCreateView.as_view(), name='survey_add'),
                    path('surveys/<int:pk>/update/', specialists.AssignParamsToSurveyView.as_view(),
                       name='survey_update'),
                    path('surveys/<int:pk>/delete/', specialists.SurveyDeleteView.as_view(),
                       name='survey_delete'),
                    path('parameters/add/', specialists.ParameterCreateView.as_view(),
                       name='parameter_add'),

                    path('orders/', OrdersListView.as_view(), name='orders_list'),
                    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='orders_detail'),
                    path('orders/orderitem/<int:pk>/', CartItemUpdateView.as_view(), name='orders_items_update'),

                ],
                'laboratory'
            ),
            namespace='specialists'
        )
    )),


    path('patients/', decorator_include(
        (login_required, patient_required), include(([
            path('surveys/', patients.SurveyListView.as_view(), name='survey_list'),
            path('surveys/<int:pk>/', patients.OrderSurveyWithParams.as_view(), name='survey_order'),
            path('cart/', cart_details_view, name='cart_details'),
            path('cart/delete_item/<int:pk>/', CartItemDeleteView.as_view(), name='cart_item_delete'),
            path('order/checkout/', order_checkout, name='order_checkout'),
            path('order/history/', UserOrdersListView.as_view(), name='order_list')
        ], 'laboratory'), namespace='patients'))),

]

medical_app/medical_app/urls.py
from django.contrib import admin
from django.urls import include, path

from users.views import users_laboratory, users_patients, users_specialists  # authentication views

urlpatterns = [
    path('', include('laboratory.urls')),  # domain views
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', users_laboratory.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patient/', users_patients.PatientSignUpView.as_view(), name='patient_signup'),
    path('accounts/signup/teacher/', users_specialists.SpecialistSignUpView.as_view(), name='specialist_signup'),

    path('admin/', admin.site.urls),

]

medical_app/laboratory/models.py
from django.db import models
from users.models import User
from django.utils import timezone


class Parameter(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Survey(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, related_name='surveys', on_delete=models.CASCADE)
    parameters = models.ManyToManyField(Parameter, blank=True, related_name="surveys_assigned")

    def __str__(self):
        return self.name

medical_app/laboratory/forms.py
from django import forms

from .models import Survey, Parameter


class AssignParamsToSurveyForm(forms.ModelForm):
    name = forms.CharField(max_length=15, label='Survey name', disabled=True)
    parameters = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=Parameter.objects.all(),
        help_text="Select parameters which should be allowed for Patients when they will be ordering this Survey")

    class Meta:
        model = Survey
        fields = ('name', 'parameters')


class OrderSurveyWithParameters(forms.Form):
    available_parameters = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, queryset=Parameter.objects.none(),
        help_text="Select the parameters you want to have checked at this Survey")

    def __init__(self, *args, **kwargs):
        survey = kwargs.pop('survey')
        super(OrderSurveyWithParameters, self).__init__(*args, **kwargs)
        self.fields['available_parameters'].queryset = survey.parameters.all()


class ParameterForm(forms.ModelForm):
    class Meta:
        model = Parameter
        fields = ('name',)


ParameterFormSet = forms.modelformset_factory(Parameter, fields=('name',), extra=5, min_num=1)

medical_app/laboratory/views/laboratory.py
from django.shortcuts import render


def home(request):
    return render(request, 'laboratory/home.html')

medical_app/laboratory/views/patients.py
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView
from cart.cart import get_cart_details_context, update_cart

from ..models import Survey
from ..forms import OrderSurveyWithParameters


class SurveyListView(ListView):
    model = Survey
    template_name = 'laboratory/patients/survey_list.html'
    context_object_name = 'surveys'
    paginate_by = 5


class OrderSurveyWithParams(FormView):
    """
    Create the CartItem with chosen Survey and Parameters; add this CartItem to the Cart
    """

    form_class = OrderSurveyWithParameters
    template_name = 'laboratory/patients/order_survey.html'
    success_url = reverse_lazy('patients:cart_details')

    def get_context_data(self, **kwargs):
        context = super(OrderSurveyWithParams, self).get_context_data(**kwargs)
        context['survey_name'] = get_object_or_404(Survey, pk=self.kwargs.get('pk')).name
        return context

    def get_form_kwargs(self):
        kwargs = super(OrderSurveyWithParams, self).get_form_kwargs()
        survey = get_object_or_404(Survey, pk=self.kwargs.get('pk'))
        kwargs.update({'survey': survey})
        return kwargs

    def form_valid(self, form):
        survey = get_object_or_404(Survey, pk=self.kwargs.get('pk'))
        parameters = form.cleaned_data['available_parameters']

        update_cart(self.request, survey, parameters)

        return super(OrderSurveyWithParams, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Parameters are missing')

        return self.render_to_response(
            self.get_context_data(request=self.request, form=form))

medical_app/laboratory/views/specialists.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import CreateView, UpdateView, ListView, DeleteView


from ..models import Survey, Parameter
from ..forms import AssignParamsToSurveyForm, ParameterFormSet, ParameterForm


class SurveyCreateView(CreateView):
    model = Survey
    fields = ('name', 'description', )
    template_name = 'laboratory/specialists/add_form.html'

    def form_valid(self, form):
        survey = form.save(commit=False)
        survey.owner = self.request.user
        survey.save()
        messages.success(self.request, 'The survey was created with success! Go ahead and add parameters now.')
        return redirect('home')

    def get_context_data(self, **kwargs):
        context = super(SurveyCreateView, self).get_context_data(**kwargs)
        context['type_to_add'] = "Survey"
        return context


class SurveyListView(ListView):
    model = Survey
    template_name = 'laboratory/specialists/list_view.html'
    context_object_name = 'surveys'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(SurveyListView, self).get_context_data(**kwargs)
        context['list_type_header'] = "All Surveys"
        return context


class SurveyDeleteView(DeleteView):
    model = Survey
    template_name = 'laboratory/specialists/survey_confirm_delete.html'
    success_url = '/'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.owner:
            messages.error(request, 'You are not allowed to delete this Survey.')
            return redirect(self.success_url)

        return super().post(request, *args, **kwargs)


class ParameterCreateView(CreateView):
    model = Parameter
    template_name = 'laboratory/specialists/add_formset.html'
    form_class = ParameterForm

    def get_context_data(self, **kwargs):
        context = super(ParameterCreateView, self).get_context_data(**kwargs)
        context['formset'] = ParameterFormSet(queryset=Parameter.objects.none())
        context['type_to_add'] = 'Parameters'
        return context

    def post(self, request, *args, **kwargs):
        formset = ParameterFormSet(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        return render(request, self.template_name, {'formset': formset})

    def form_valid(self, formset):
        instances = formset.save(commit=False)
        for instance in instances:
            instance.save()
        messages.success(self.request, "The new Parameters were created with success! "
                                       "Go ahead and assign them to Surveys or create new Parameters!")
        return redirect('specialists:parameter_add')


class AssignParamsToSurveyView(UpdateView):
    model = Survey
    form_class = AssignParamsToSurveyForm
    template_name = 'laboratory/specialists/update_view.html'

    def form_valid(self, form):
        params = form.cleaned_data['parameters']
        survey = form.save(commit=False)
        survey.parameters.add(*params)
        survey.save()
        messages.success(self.request, "You have just updated parameters assigned to the survey!")
        return redirect('specialists:survey_update', survey.pk)

    def get_context_data(self, **kwargs):
        context = super(AssignParamsToSurveyView, self).get_context_data(**kwargs)
        context['type_to_add'] = "Parameters to the Survey"
        return context

medical_app/laboratory/templates/laboratory/specialists/add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Add a new {{ type_to_add }}</h2>

  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'home' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>

  {% if update_view and survey.owner == user %}
    <div>
      <a type="button" class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'specialists:survey_delete' object.id %}">Delete</a>
    </div>
  {% endif %}
{% endblock %}

medical_app/laboratory/templates/laboratory/specialists/add_formset.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Add a new {{ type_to_add }}</h2>

  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form|crispy }}<br>
        {% endfor %}

        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'home' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>

  {% if update_view and survey.owner == user %}
    <div>
      <a type="button" class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'specialists:survey_delete' object.id %}">Delete</a>
    </div>
  {% endif %}
{% endblock %}

medical_app/laboratory/templates/laboratory/specialists/list_view.html
{% extends "base.html" %}
{% block content %}

    <h1 class="mb-3">{{list_type_header}} ({{ page_obj.paginator.count }})</h1>





     <ul class="list-group">
         {% for survey in surveys %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'specialists:survey_update' survey.pk %}">{{ survey.name }}</a>
                <span class="badge badge-primary badge-pill">Parameters allowed: {{ survey.parameters.count }}</span>
              </li>
         {% endfor %}
    </ul>


    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

medical_app/laboratory/templates/laboratory/specialists/survey_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete survey</legend>
                <h2>Are you sure you want to delete the survey "{{ object.name }}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'specialists:survey_update' object.id %}">Cancel</a>

            </div>

        </form>
    </div>
{% endblock content %}

medical_app/laboratory/templates/laboratory/specialists/update_view.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Add a new {{ type_to_add }}</h2>

  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'home' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a type="button" {% if object.owner == user %}class="btn btn-outline-danger btn-sm mt-1 mb-1"{% else %}class="btn btn-secondary btn-sm mt-1 mb-1 disabled"{%endif%} href="{% url 'specialists:survey_delete' object.id %}">Delete</a>

      </form>
    </div>
  </div>

{% endblock %}