medical_app/laboratory/urls.py
from django.urls import include, path

from .views import laboratory, specialists, patients
from cart.views import CartItemDeleteView, cart_details_view, CartItemUpdateView
from orders.views import order_checkout, UserOrdersListView, OrdersListView, edit_order_items, OrdersDetailView


from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from users.decorators import specialist_required, patient_required


urlpatterns = [
    path('', laboratory.home, name='home'),

    path('specialists/', decorator_include(
        (login_required, specialist_required), include(
            (
                [
                    path('surveys/', specialists.SurveyListView.as_view(), name='survey_list'),
                    path('surveys/add/', specialists.SurveyCreateView.as_view(), name='survey_add'),
                    path('surveys/<int:pk>/update/', specialists.AssignParamsToSurveyView.as_view(),
                       name='survey_update'),
                    path('surveys/<int:pk>/delete/', specialists.SurveyDeleteView.as_view(),
                       name='survey_delete'),
                    path('parameters/add/', specialists.ParameterCreateView.as_view(),
                       name='parameter_add'),

                    path('orders/', OrdersListView.as_view(), name='orders_list'),
                    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='orders_detail'),
                    path('orders/orderitem/<int:pk>/', CartItemUpdateView.as_view(), name='orders_items_update'),

                ],
                'laboratory'
            ),
            namespace='specialists'
        )
    )),


    path('patients/', decorator_include(
        (login_required, patient_required), include(([
            path('surveys/', patients.SurveyListView.as_view(), name='survey_list'),
            path('surveys/<int:pk>/', patients.OrderSurveyWithParams.as_view(), name='survey_order'),
            path('cart/', cart_details_view, name='cart_details'),
            path('cart/delete_item/<int:pk>/', CartItemDeleteView.as_view(), name='cart_item_delete'),
            path('order/checkout/', order_checkout, name='order_checkout'),
            path('order/history/', UserOrdersListView.as_view(), name='order_list')
        ], 'laboratory'), namespace='patients'))),

]

medical_app/medical_app/urls.py
from django.contrib import admin
from django.urls import include, path

from users.views import users_laboratory, users_patients, users_specialists  # authentication views

urlpatterns = [
    path('', include('laboratory.urls')),  # domain views
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', users_laboratory.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patient/', users_patients.PatientSignUpView.as_view(), name='patient_signup'),
    path('accounts/signup/teacher/', users_specialists.SpecialistSignUpView.as_view(), name='specialist_signup'),

    path('admin/', admin.site.urls),

]

medical_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/rowselected.js' %}"></script>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"  crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <meta charset="UTF-8">


    <title>{% block title %}Laboratory App{% endblock %}</title>

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Laboratory</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'signup' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
          {% block content %}{% endblock %}
        </div>
        {% if user.is_authenticated %}

        <div class="col-md-4">
          <div class="content-section">
            <p class='text-muted'>
                  <div class="list-group">
                        {% if user.is_patient %}
                            <a href="{% url 'patients:survey_list' %}" class="list-group-item list-group-item-primary">Order new surveys</a>
                            <a href="{% url 'patients:cart_details' %}" class="list-group-item list-group-item-primary">Your current order</a>
                            <a href="{% url 'patients:order_list' %}" class="list-group-item list-group-item-primary">Your surveys history</a>
                        {% else %}
                            <a href="{% url 'specialists:survey_list' %}" class="list-group-item list-group-item-primary">Surveys list</a>
                            <a href="{% url 'specialists:survey_add' %}" class="list-group-item list-group-item-primary">Add new Survey</a>
                            <a href="{% url 'specialists:parameter_add' %}" class="list-group-item list-group-item-primary">Add new Parameter</a>
                            <a href="{% url 'specialists:orders_list' %}" class="list-group-item list-group-item-primary">All orders</a>


                        {% endif %}
                  </div>

            </p>
          </div>
        </div>
      </div>
      {% endif %}

    </main>

    {% block extrajavascript %}{% endblock extrajavascript %}

</body>
</html>