medical_app/laboratory/urls.py
from django.urls import include, path

from .views import laboratory, specialists, patients
from cart.views import CartItemDeleteView, cart_details_view, CartItemUpdateView
from orders.views import order_checkout, UserOrdersListView, OrdersListView, edit_order_items, OrdersDetailView


from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from users.decorators import specialist_required, patient_required


urlpatterns = [
    path('', laboratory.home, name='home'),

    path('specialists/', decorator_include(
        (login_required, specialist_required), include(
            (
                [
                    path('surveys/', specialists.SurveyListView.as_view(), name='survey_list'),
                    path('surveys/add/', specialists.SurveyCreateView.as_view(), name='survey_add'),
                    path('surveys/<int:pk>/update/', specialists.AssignParamsToSurveyView.as_view(),
                       name='survey_update'),
                    path('surveys/<int:pk>/delete/', specialists.SurveyDeleteView.as_view(),
                       name='survey_delete'),
                    path('parameters/add/', specialists.ParameterCreateView.as_view(),
                       name='parameter_add'),

                    path('orders/', OrdersListView.as_view(), name='orders_list'),
                    path('orders/<int:pk>/', OrdersDetailView.as_view(), name='orders_detail'),
                    path('orders/orderitem/<int:pk>/', CartItemUpdateView.as_view(), name='orders_items_update'),

                ],
                'laboratory'
            ),
            namespace='specialists'
        )
    )),


    path('patients/', decorator_include(
        (login_required, patient_required), include(([
            path('surveys/', patients.SurveyListView.as_view(), name='survey_list'),
            path('surveys/<int:pk>/', patients.OrderSurveyWithParams.as_view(), name='survey_order'),
            path('cart/', cart_details_view, name='cart_details'),
            path('cart/delete_item/<int:pk>/', CartItemDeleteView.as_view(), name='cart_item_delete'),
            path('order/checkout/', order_checkout, name='order_checkout'),
            path('order/history/', UserOrdersListView.as_view(), name='order_list')
        ], 'laboratory'), namespace='patients'))),

]

medical_app/medical_app/urls.py
from django.contrib import admin
from django.urls import include, path

from users.views import users_laboratory, users_patients, users_specialists  # authentication views

urlpatterns = [
    path('', include('laboratory.urls')),  # domain views
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', users_laboratory.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patient/', users_patients.PatientSignUpView.as_view(), name='patient_signup'),
    path('accounts/signup/teacher/', users_specialists.SpecialistSignUpView.as_view(), name='specialist_signup'),

    path('admin/', admin.site.urls),

]

medical_app/orders/models.py
from django.db import models
from users.models import User
from cart.models import Cart

STATUS_CHOICES = (
    ("P", "Processed"),
    ("F", "Finished"),
)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='order')
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="P")

    def __str__(self):
        return f'Order ID: {self.pk} ordered by userID:{self.user.pk}'

    def get_number_of_surveys(self):
        return self.cart.cart_items.count()

medical_app/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, UpdateView, DetailView
from django.db.models.functions import Now
from django.forms import modelformset_factory, inlineformset_factory
from cart.models import Cart, CartItem, ParameterWithResult
from cart.forms import ParameterWithResultForm, ParameterWithResultFormSet
from django.conf import settings
from .models import Order


def order_checkout(request):
    """Create Order based on the Cart attached to the current session """

    template = 'orders/user_orders_list.html'
    try:
        the_id = request.session[settings.CART_SESSION_ID]
    except:
        return redirect('patients:cart_details')

    cart = Cart.objects.get(id=the_id)
    Order.objects.create(cart=cart, user=request.user)
    cart.ordered_at = Now()

    # delete the Cart ID from the session
    del request.session[settings.CART_SESSION_ID]

    return render(request, template, {})


class UserOrdersListView(ListView):
    """List all orders made by the user"""

    template_name = 'orders/user_orders_list.html'
    context_object_name = 'cart_items'

    def get_queryset(self):

        # get all orders of this user
        orders = self.request.user.orders.all().order_by('-created_at')

        # and all carts attached to those orders
        ordered_carts = [order.cart for order in orders]

        # having all ordered carts, extract CartItems
        ordered_cart_items = []
        for cart in ordered_carts:
            ordered_cart_items.extend(cart.cart_items.all())

        return ordered_cart_items


class OrdersListView(ListView):
    """List all Orders with the Pending status ??"""
    model = Order
    template_name = 'orders/orders_list.html'
    context_object_name = 'orders'
    ordering = ['-status']
    paginate_by = 4


class OrdersDetailView(DetailView):
    model = Order
    template_name = 'orders/orders_detail.html'
    ordering = ['-created_at']



#
# def edit_order_items(request, pk):
#     template_name = 'orders/inlineformset.html'
#     OrderFormSet = inlineformset_factory(CartItem, ParameterWithResult, fields=('parameter', 'result'), extra=3)
#
#     order = get_object_or_404(Order, pk=pk)
#     ordered_cart_items_pks = [i.pk for i in order.cart.cart_items.all()]
#     params_and_results = ParameterWithResult.objects.filter(pk__in=ordered_cart_items_pks)
#
#     formset = OrderFormSet(instance=order.cart.cart_items.all(), queryset=params_and_results)
#     # form = OrderForm(initial={'customer':customer})
#     if request.method == 'POST':
#         print('Printing POST:', request.POST)
#         # form = OrderForm(request.POST)
#         formset = OrderFormSet(request.POST)
#         if formset.is_valid():
#             formset.save()
#             return redirect('specialists:orders_list')
#
#     context = {'form': formset}
#     return render(request, template_name, context)
#


    #
    # """View for updating all order items at once """
    #
    # template_name = 'orders/order_items_update_formset.html'
    #
    # order = get_object_or_404(Order, pk=pk)
    # ordered_cart_items_pks = [i.pk for i in order.cart.cart_items.all()]
    # params_and_results = ParameterWithResult.objects.filter(pk__in=ordered_cart_items_pks)
    #
    # ProductFormSet = modelformset_factory(ParameterWithResult, fields=('parameter', 'result'), extra=0)
    # data = request.POST or None
    #
    # formset = ProductFormSet(data=data, queryset=params_and_results)
    #
    # if request.method == 'POST' and formset.is_valid():
    #     formset.save()
    #     return redirect('specialists:orders_list')
    #
    # return render(request, template_name, {'formset': formset})
#


class ParameterWithResultsUpdateView(UpdateView):
    model = ParameterWithResult
    template_name = 'orders/order_items_update_formset.html'
    form_class = ParameterWithResult

    def get_context_data(self, **kwargs):
        context = super(ParameterWithResultsUpdateView, self).get_context_data(**kwargs)
        context['formset'] = ParameterWithResultFormset(queryset=Parameter.objects.none())


def edit_order_items(request, pk):
    """View for updating all order items at once """



    """View for updating all order items at once """

    template_name = 'orders/order_items_update_formset.html'

    order = get_object_or_404(Order, pk=pk)
    ordered_cart_items_pks = [i.pk for i in order.cart.cart_items.all()]
    params_and_results = ParameterWithResult.objects.filter(pk__in=ordered_cart_items_pks)
    print(len(params_and_results))

    ProductFormSet = modelformset_factory(ParameterWithResult, fields=('parameter', 'result'), exclude=('parameter',), extra=0)
    data = request.POST or None

    formset = ProductFormSet(data=data, initial=params_and_results)

    if request.method == 'POST' and formset.is_valid():
        formset.save(commit=True)

        return redirect('specialists:orders_list')

    return render(request, template_name, {'formset': formset})


    # # template_name = 'orders/inlineformset.html'
    # template_name = 'orders/order_items_update_formset.html'
    #
    # order = get_object_or_404(Order, pk=pk)
    # ordered_cart_items_pks = [i.pk for i in order.cart.cart_items.all()]
    # params_and_results = ParameterWithResult.objects.filter(pk__in=ordered_cart_items_pks)
    # print(params_and_results)
    #
    # ProductFormSet = modelformset_factory(ParameterWithResult, fields=('parameter', 'result', 'cart_item'), can_delete=False, extra=0)
    # data = request.POST or None
    #
    # # formset = ProductFormSet(data=data, queryset=params_and_results)
    # formset = ProductFormSet(initial=params_and_results)
    #
    # if request.method == 'POST' and formset.is_valid():
    #     formset.data = data
    #     formset.save()
    #     return redirect('specialists:orders_list')
    #
    # return render(request, template_name, {'formset': formset})

medical_app/orders/templates/orders/all_orders_list.html
{% extends 'base.html' %}
{% block title %}
    Orders history
{% endblock %}


{% block content %}

<div class="container">
    <div class="row" style="margin-top: 6%">
        <table class="table table-striped table-hover">
            <thead style="background-color: #5AC8FA">
                <tr>
                    <th>Order ID</th>
                    <th>Surveys ordered</th>
                    <th>Created at</th>
                    <th>Finished at</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                    <tr>
                        <td><a href="{% url 'specialists:orders_items_update' order.pk %}">{{ order.pk }}</a></td>
                        <td>{{ order.get_number_of_surveys }}</td>
                        <td>{{ order.created_at }}</td>
                        <td>{{ item.finished_at }}</td>
                        <td>{{ order.status }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}

{% endblock %}

medical_app/orders/templates/orders/inlineformset.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}


<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<form action="" method="POST">
				{% csrf_token %}
				{{ form.management_form }}
				{% for field in form %}
					{{field}}
					<hr>
				{% endfor %}
				
				<input type="submit" name="Submit">
			</form>

		</div>
	</div>
</div>


{% endblock %}

medical_app/orders/templates/orders/order_items_update_formset.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update surveys results</h1>
  <h1>IT IS NOT WORKING FINE yet...</h1>
  <form method="post">
    {% csrf_token %}
    {{ formset.as_p }}
    <input type="submit" value="save all products">
  </form>
{% endblock %}

medical_app/orders/templates/orders/orders_detail.html
{% extends 'base.html' %}
{% block title %}
    Order details
{% endblock %}


{% block content %}

<h1>Ordered by: {{ object.user }}, at: {{ object.created_at }}</h1>

<div class="container">
    <div class="row" style="margin-top: 6%">
        <table class="table table-hover">
            <thead style="background-color: #5AC8FA">
                <tr>
                    <th>ID</th>
                    <th>Survey</th>
                    <th>Parameters chosen</th>
                    <th>Finished at</th>
                </tr>
            </thead>
            <tbody>

            {% for cart_item in object.cart.cart_items.all %}
                <tr data-href="{% url 'specialists:orders_items_update' cart_item.pk %}">
                    <td>{{ cart_item.pk }}</td>
                    <td>{{ cart_item.survey }}</td>
                    <td>{{ cart_item.parameters.count }}</td>
                    <td>{{ cart_item.finished_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}

{% endblock %}

medical_app/orders/templates/orders/orders_list.html
{% extends 'base.html' %}
{% block title %}
    Orders history
{% endblock %}


{% block content %}

<div class="container">
    <div class="row" style="margin-top: 6%">
        <table class="table table-hover">
            <thead style="background-color: #5AC8FA">
                <tr>
                    <th>Order ID</th>
                    <th>Surveys ordered</th>
                    <th>Created at</th>
                    <th>Finished at</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr data-href="{% url 'specialists:orders_detail' order.pk %}">
                    <td>{{ order.pk }}</a></td>
                    <td>{{ order.get_number_of_surveys }}</td>
                    <td>{{ order.created_at }}</td>
                    <td>{{ item.finished_at }}</td>
                    <td>{{ order.status }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}





<!--<script>-->
<!--&lt;!&ndash;    document.addEventListener("DOMContentLoaded", () => {&ndash;&gt;-->
<!--&lt;!&ndash;        const rows = document.querySelectorAll("tr[data-href]");&ndash;&gt;-->
<!--&lt;!&ndash;        rows.forEach(row => {&ndash;&gt;-->
<!--&lt;!&ndash;            row.addEventListener("click", () => {&ndash;&gt;-->
<!--&lt;!&ndash;                window.location.href = row.dataset.href;&ndash;&gt;-->
<!--&lt;!&ndash;            });&ndash;&gt;-->
<!--&lt;!&ndash;        });&ndash;&gt;-->
<!--&lt;!&ndash;    });&ndash;&gt;-->

<!--    $(document).ready(function () {-->
<!--        $(document.body).on("click", "tr[data-href]", function () {-->
<!--            window.location.href = this.dataset.href;-->
<!--        });-->
<!--    });-->

<!--</script>-->

{% endblock %}

medical_app/orders/templates/orders/user_orders_list.html
{% extends 'base.html' %}
{% block title %}
    Orders history
{% endblock %}


{% block content %}
{% if empty %}
    <h1>{{ empty_message }}</h1>
{% else %}


    <div class="container">
        <div class="row" style="margin-top: 6%">
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Survey</th>
                        <th>Parameter</th>
                        <th>Result</th>
                        <th>Finished at</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart_items %}
                    {% for param_with_result in item.parameters_results.all %}
                        <tr>
                            <td>{{ item.survey.name }}</td>
                            <td>{{ param_with_result.parameter.name }}</td>
                            <td>{{ param_with_result.result }}</td>
                            <td>{{ item.finished_at }}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}
{% endblock %}